// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7pi4O-m-3RW4TxFsBapLSf4NOeoF3L-s',
    appId: '1:849813957735:web:f550fd632644d1d49078c2',
    messagingSenderId: '849813957735',
    projectId: 'login-form-8f97b',
    authDomain: 'login-form-8f97b.firebaseapp.com',
    storageBucket: 'login-form-8f97b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrd-mOSO3vT1DuyxBbnt6cYBjoVhe-ous',
    appId: '1:849813957735:android:b9456056223ea1979078c2',
    messagingSenderId: '849813957735',
    projectId: 'login-form-8f97b',
    storageBucket: 'login-form-8f97b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmbfGlMXVhEsZOx11IZIMtSFqfDR_DkeA',
    appId: '1:849813957735:ios:e71f1ff81f5e70869078c2',
    messagingSenderId: '849813957735',
    projectId: 'login-form-8f97b',
    storageBucket: 'login-form-8f97b.appspot.com',
    iosClientId: '849813957735-r3h4gdud5nrku690mqgoq0kqemgjgniq.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmbfGlMXVhEsZOx11IZIMtSFqfDR_DkeA',
    appId: '1:849813957735:ios:e71f1ff81f5e70869078c2',
    messagingSenderId: '849813957735',
    projectId: 'login-form-8f97b',
    storageBucket: 'login-form-8f97b.appspot.com',
    iosClientId: '849813957735-r3h4gdud5nrku690mqgoq0kqemgjgniq.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
}
